### ISSUE TITLE
Option to build without pushing the image

### ISSUE THREAD

**Issue by jtpio** [machine-learning-apps/repo2docker-action#13]
Thanks for this cool GitHub Action!

It looks like it could be useful to have control on whether to push the image or not, after the `repo2docker` build has completed.

For example, the build would be triggered when someone opens a PR, without pushing the image to DockerHub. Maybe something like the following:

```yaml
name: Build Notebook Container
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@master

    - name: try-local-build
      uses: machine-learning-apps/repo2docker-action@master
      with:
        push: no
```

This would make it possible to check whether the repo correctly builds before merging into master.
