### ISSUE TITLE
Repo2Docker Example Brainstorming

### ISSUE THREAD

**Issue by hamelsmu** [machine-learning-apps/repo2docker-action#17]
I plan on fleshing out the docs in this repo a bit more to add relevant examples that illustrate practical use cases for using repo2docker

1. Have Actions comment with a Binder badge automatically on a PR, or with a chatops command that corresponds to the branch referenced in the PR.  This is so reviewers can get easy access to a live notebook to review notebooks in the PR with just a click.  Will look something like this:

    ![image](https://user-images.githubusercontent.com/1483922/82162778-e767b200-985b-11ea-9c1a-6d3282474daf.png)

2. Automatically launch notebooks when a PR is opened or with a chatops command on [paperspace gradient](https://gradient.paperspace.com/).  

    A rough sketch is something like this

    ```yaml
    ...
      - name: build-environment
        id: repo2docker
        uses: machine-learning-apps/repo2docker-action
        with:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            IMAGE_NAME: "hamelsmu/repo2docker-test"

      - name: paperspace-deploy
        id: paperspace
        run: |
            pip install gradient
            gradient apiKey ${PAPERSPACE_TOKEN}
            gradient jobs create --container ${IMAGE_NAME} --projectId ${PAPERSPACE_PROJECT_ID} --machineType K80 --ports 8888:8888
        env:
            PAPERSPACE_TOKEN: ${{ secrets.PAPERSPACE_TOKEN }}
            PAPERSPACE_PROJECT_ID: ${{ secrets.PAPERSPACE_PROJECT_ID }}
            IMAGE_NAME: ${{ steps.repo2docker.outputs.IMAGE_SHA_NAME }}

    ```

3. Launch repo2docker images on the major clouds: GCP, AWS, Azure and maybe [FloydHub](https://www.floydhub.com/pricing)

    A rough sketch looks like this on GCP - Google Cloud Functions 

    ```yaml
    ....
      - uses: exelban/gcloud@master
        env:
            PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
            APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            IMAGE_NAME: ${{ steps.repo2docker.outputs.IMAGE_SHA_NAME }}
        with:
            args: --quiet beta run deploy notebook-serve-action --allow-unauthenticated --platform managed --region us-west1 --image $IMAGE_NAME
    ```

4.  Examples with [codespaces](https://github.com/features/codespaces/)

----

### Other Ideas: TBD

@betatim, @willingc @neovintage any other ideas?  The possibilities are so exciting, would love your ideas and thoughts!
