### ISSUE TITLE
Expected repo structure and use with Binder config files?

### ISSUE THREAD

**Issue by matthewfeickert** [machine-learning-apps/repo2docker-action#26]
@hamelsmu Thanks very much for being so responsive on [our discussion over on the Jupyter Discourse](https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956/8). To avoid derailiig the original topic of that discussion though, I thought I'd ask about the specifics of [`pyhf`](https://github.com/scikit-hep/pyhf)'s situation here.

At the moment I have a branch on `pyhf` that has the following `.github/workflows/binder.yml` file:

```yaml
name: Build Binder Image
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Update jupyter dependencies with repo2docker
      uses: machine-learning-apps/repo2docker-action@0.1

      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "pyhf/binder"
        NOTEBOOK_USER: "jovyan"
```

Aside first: If you do

```
$ docker pull pyhf/binder:latest # This is huge, sorry
$ docker run --rm -it -p 8888:8888 pyhf/binder:latest /bin/bash -c 'echo $USER'
matthewfeickert
```

but it seems that this should be `jovyan` given the above, not `matthewfeickert`, no?

`</aside>`

You had mentioned on Discourse that

> The GitHub Action as works today only expects that you do NOT have a `.binder/` or `binder/` directory at the root of the repo

As [`pyhf` _does_ have a top level `binder/` directory](https://github.com/scikit-hep/pyhf/tree/master/binder) with multiple files inside of it, is this a problem that can be dealt with? I'm thinking maybe not as is(?) given that `repo2docker` will look in `/binder` first and build according to those config files. If we were to place the `Dockerfile` that we want Binder to try to use with your action (which would basically be 1 line: `FROM pyhf/binder:latest`) in `binder/` then our other config files would be ignored, and if we place the `Dockerfile` outside of `binder/` then it is ignored. If I have this right, then it seems like this is an impass. If I'm wrong &mdash; that's great! If not, can we help?

> let me know what part you need help on, (maybe its just getting started with Actions?). Or an example? Let me know how I can help.

`pyhf` is a [huge fan of GitHub Actions](https://github.com/scikit-hep/pyhf/tree/master/.github/workflows), and you can say that we maybe even overuse/abuse them. If you have an example project of yours that is public that would be a help, though maybe the above discussion makes it not relevant at the moment.

cc @lukasheinrich @kratsg
